### ISSUE TITLE
Cannot access application websocket

### ISSUE THREAD

**Issue by LucaAndrei** [jkrup/meteor-now#36] opened 2017-03-17 11:39 UTC
Hi
I'm going to post the same issue that I have created and described in the `now` package, maybe it's related to this package after all
[https://github.com/zeit/now-cli/issues/389](url)

**Comment by purplecones** [comment] 2017-03-17 12:30
@LucaAndrei I'm somewhat unclear what you are trying to do. Can you deploy the same app on a different provider (Digital Ocean, Galaxy, AWS, etc.) and provide steps to reproduce your issue?
This way we can replicate the steps on both the other deployment and the now deployment and see whats different.

**Comment by purplecones** [comment] 2017-03-17 14:47
Was able to connect to a [meteor app](https://todos-udkjndwlvw.now.sh/) deployed to `now` with a DDP connection from a [non-meteor](https://github.com/purplecones/node-ddp-issue-test) app running locally. To test, clone non-meteor repo, `yarn` > `yarn run dev` to see an output of the lists that are created on the meteor app.

Doesn't appear to be an issue with `now` or `meteor-now`.

**Comment by purplecones** [comment] 2017-03-19 18:52
Closing issue since it doesn't appear to be related to `now` or `meteor-now`.

**Closed by purplecones** 2017-03-19 18:52 UTC
