### ISSUE TITLE
MONGO_OPLOG_URL and crashing deployments with mongodb atlas URLs

### ISSUE THREAD

**Issue by eyeswideopen** [jkrup/meteor-now#58] opened 2017-06-06 07:08 UTC
I'm having problems deploying when using a mongo db on atlas.
`MongoError: seed list contains no mongos proxies, replicaset connections requires the parameter replicaSet to be supplied in the URI or options object, mongodb://server:port/db?replicaSet=name`

keeps occuring even though my db URL looks like:
`mongodb://<MYUSER>:<MYPASSWORD>@wave-shard-00-00-6ml1d.mongodb.net:27017,wave-shard-00-01-6ml1d.mongodb.net:27017,wave-shard-00-02-6ml1d.mongodb.net:27017/admin?ssl=true&replicaSet=Wave-shard-0&authSource=admin`

Follow up question:
is it possible to provide the MONGO_OPLOG_URL as an environment variable?

**Comment by jkrup** [comment] 2017-06-06 12:46
How are you passing in your db URL? I am using atlas w/ replica sets by saving my mongourl in a `now secret` like this:
```
now secrets add mongourl 'mongodb://<MYUSER>:<MYPASSWORD>@wave-shard-00-00-6ml1d.mongodb.net:27017,wave-shard-00-01-6ml1d.mongodb.net:27017,wave-shard-00-02-6ml1d.mongodb.net:27017/admin?ssl=true&replicaSet=Wave-shard-0&authSource=admin'
```

Then to deploy:
```
meteor-now -e MONGO_URL=@mongourl -e ROOT_URL=...
```

You should be able to pass in a MONGO_OPLOG_URL the same way like this:
```
now secrets add mongooplogurl _________________________
meteor-now -e MONGO_URL=@mongourl -e MONGO_OPLOG_URL=@mongooplogurl -e ROOT_URL=...
```

I think because of the special characters in my password and the `?` typing it directly into the terminal (as opposed to inside of a `now secret` makes it sometimes escape characters and therefore not work properly

**Comment by jkrup** [comment] 2017-08-31 18:14
I have gotten `MONGO_OPLOG_URL`s working in my deploys so I am going to close this issue. If you are able to reproduce please let me know :)

**Closed by jkrup** 2017-08-31 18:14 UTC
